version: '3'
services:
  app:
    image: 'express-app'
    build: './app/'
    container_name: 'express_${APP_NAME}'
    ports:
      - '4000:4000'
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: 'mongo_${APP_NAME}'
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-app

  react_app:
    image: 'react-app'
    build: './client/'
    stdin_open: true

    ports:
      - '3000:3000'
    container_name: 'react_${APP_NAME}'
    restart: unless-stopped
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
